### ISSUE TITLE
No sql file, Please provide a complete sql, Thanks.

### ISSUE THREAD

**Issue by davidWeiZhou** [defshine/flaskblog#1]
db.sql only CREATE SCHEMA flaskblog, not creat any table in flaskblog database, Could you provide a full sql?

**Comment by davidWeiZhou** [comment]
I want use this blog to study flask and mysql. thanks.

**Comment by defshine** [comment]
pull this project and install all requirements
After create schema in mysql ,run create_db command in [manage.py](https://github.com/defshine/flaskblog/blob/master/manage.py),it will create all tables
